// Bake the heavy engine assets and the example lectures into bundled modules so
// the playground can compile entirely in the browser (no fs, no server).
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { loadNodeAssets } from "@chalk/render-slides";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const examplesDir = join(root, "..", "..", "examples");
const genDir = join(root, "src", "generated");
mkdirSync(genDir, { recursive: true });

// 1) Engine assets (KaTeX CSS+fonts, KaTeX JS, runtime IIFE) as string literals.
const assets = loadNodeAssets();
writeFileSync(
  join(genDir, "assets.ts"),
  `// AUTO-GENERATED by scripts/prebuild.mjs — do not edit.
import type { DeckAssets } from "@chalk/render-slides/core";
export const ASSETS: DeckAssets = {
  katexCss: ${JSON.stringify(assets.katexCss)},
  katexJs: ${JSON.stringify(assets.katexJs)},
  runtimeJs: ${JSON.stringify(assets.runtimeJs)},
};
`,
);

// 2) The example lectures (curated order shown in the dropdown).
const manifest = [
  { file: "limits.chalk", label: "Limits & Continuity — everything" },
  { file: "morphing.chalk", label: "Equation morphing" },
  { file: "graphing.chalk", label: "2D graphing scene" },
  { file: "surfaces.chalk", label: "3D surfaces (WebGL)" },
];
const examples = manifest.map((m) => ({
  id: m.file.replace(/\.chalk$/, ""),
  label: m.label,
  source: readFileSync(join(examplesDir, m.file), "utf8"),
}));
writeFileSync(
  join(genDir, "examples.ts"),
  `// AUTO-GENERATED by scripts/prebuild.mjs — do not edit.
export interface Example { id: string; label: string; source: string; }
export const EXAMPLES: Example[] = ${JSON.stringify(examples, null, 2)};
`,
);

const kb = (n) => `${Math.round(n / 1024)}KB`;
console.log(
  `prebuild: assets (css ${kb(assets.katexCss.length)}, js ${kb(
    assets.katexJs.length,
  )}, runtime ${kb(assets.runtimeJs.length)}), ${examples.length} examples`,
);
